### 获取用户信息
GET http://localhost:9990/?id=222

### 获取用户信息
POST http://localhost:9999
Content-Type: application/json

{
  "service": "org.sunny.sunnyprcdemoapi.interfaces.UserService",
  "method": "getUserById",
  "params": [
    "1"
  ]
}

### 获取订单信息
POST http://localhost:9999
Content-Type: application/json

{
  "service": "org.sunny.sunnyprcdemoapi.interfaces.OrderService",
  "method": "getOrderById",
  "params": [
    200
  ]
}