server:
  port: 9990

sunnyrpc:
  providers: http://localhost:9997/,http://localhost:9998/,http://localhost:9999/
  zkServer: 8.141.93.226:2181
  zkRoot: sunnyrpc
  app.id: app1
  app.namespace: public
  app.env: dev
  retries: 2
  timeout: 5

logging:
  level:
    root: info
    org.sunny.sunnyrpccore: debug