server:
  port: 9990

sunnyrpc:
  register:
    type: zookeeper/nacos
  transection:
    type: http/netty
  zk:
    server: 8.141.93.226:2181
    root: sunnyrpc
  app:
    id: app1
    namespace: public
    env: dev
  consumer:
    retries: 2
    timeout: 1
    grayRatio: 10 # 0-100
    faultLimit: 10 # 30s 内10次错误则隔离
    halfOpenInitialDelay: 10000
    halfOpenDelay: 60000
    
logging:
  level:
    root: info
    org.sunny.sunnyrpccore: debug