server:
  port: 9990

sunnyrpc:
  registry:
    name: nacos
  transection:
    name: http/netty
  zk:
    server: 8.141.93.226:2181
    root: sunnyrpc
  sunny-registry:
    serverList:
      - http://127.0.0.1:8484
      - http://127.0.0.1:8485
      - http://127.0.0.1:8486
  nacos-registry:
    server-addrs:
      - 192.168.2.102:8848
    user-name: nacos
    password: nacos
    namespace: sunny-rpc
  app:
    id: app1
    namespace: public
    env: dev
  consumer:
    retries: 2
    timeout: 1
    grayRatio: 10 # 0-100
    faultLimit: 10 # 30s 内10次错误则隔离
    halfOpenInitialDelay: 10000
    halfOpenDelay: 60000
    
logging:
  level:
    root: info
    org.sunny.sunnyrpccore: debug