server:
  port: 9999
  tomcat:
    connection-timeout: 60000
sunnyrpc:
  registry:
    #    name: zk
    name: sunny-registry
  zk:
    server: 8.141.93.226:2181
    root: sunnyrpc
  sunny-registry:
    serverList:
      - http://127.0.0.1:8484
      - http://127.0.0.1:8485
      - http://127.0.0.1:8486
  app:
    id: app1
    namespace: public
    env: dev
  provider:
    metas:
      dc: bj
      gray: false
      unit: B001
      tc: 25
logging:
  level:
    root: info
    org.sunny.sunnyrpccore: debug