server:
  port: 9999
  tomcat:
    connection-timeout: 60000
sunnyrpc:
  zk:
    server: 8.141.93.226:2181
    root: sunnyrpc
  app:
    id: app1
    namespace: public
    env: dev
  provider:
    metas:
      dc: bj
      gray: false
      unit: B001
      
logging:
  level:
    root: debug
    org.sunny.sunnyrpccore: debug