server:
  port: 9999
  tomcat:
    connection-timeout: 60000
sunnyrpc:
  zkServer: 8.141.93.226:2181
  zkRoot: sunnyrpc
  app.id: app1
  app.namespace: public
  app.env: dev
  provider:
    metas:
      dc: bj
      gray: false
      unit: B001
      
logging:
  level:
    root: debug
    org.sunny.sunnyrpccore: debug